name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install meson
      run: sudo apt install meson
    - name: Run meson
      run: meson build/
    - name: Build the project
      run: ninja -C build/
